name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn' # GitHub cashar nu dina Yarn-paket

      - name: 📦 Install EAS CLI
        # Vi använder yarn för att installera verktyget globalt
        run: yarn global add eas-cli

      - name: 📦 Install dependencies
        # Detta installerar alla paket i din package.json med Yarn
        run: yarn install

      - name: 🚀 Build APK
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
