name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: 📦 Install EAS CLI
        # We install it manually to avoid the yarn error in the expo-action
        run: npm install -g eas-cli

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build APK
        # We call EAS directly instead of using the wrapper action
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
